For each item, talk about:

- How I do thing
- What resources I used to learn to do things this way

# Setting Myself Up for Success

## Software: R + RStudio

### Why I Don't Work Just in R

### Why I Use RStudo, not something like R Commander

### RStudio Options

Uncheck load data on start new session

## Code style

### Examples of other style guides

- http://jef.works/R-style-guide/
- https://style.tidyverse.org/ + https://styler.r-lib.org/index.html
- https://google.github.io/styleguide/Rguide.xml
- https://ropensci.github.io/dev_guide/
- https://csgillespie.github.io/efficientR/


### My style preferences

- Spaces between things
- Line breaks
- Put all packages at top of script

## Working with Files

### Directory organization

#### Use data/data-raw structure
#### Naming files

https://speakerdeck.com/jennybc/how-to-name-files?slide=3)

## Packages

### Where do I find packages?

### How do I evaluate packages?

### Why I Use the Tidyverse 

- https://joss.theoj.org/papers/10.21105/joss.01686

## Workflow
### When to use .R vs .Rmd

Break up data cleaning (R script) and reporting (RMarkdown)



### Load all data at top

### Add sections in R scripts to enable TOC


## Git/GitHub

Pluses
- Hard to get set up
Minuses
- Multiple people can work at a time
- Version control
- Branching

### As compared to Google Drive, Dropbox, etc.

Pluses
- Easy

Minuses
- Only one person can work at a time
- No version control
        

# Working with Data

## Data Importing

### Why to use read_csv not read.csv
### clean_names() function

### Variable and value labels

#### Codebooks

https://rubenarslan.github.io/codebook/
https://cran.r-project.org/web/packages/vtable/index.html
https://cran.r-project.org/web/packages/sjlabelled/index.html
       
## Examining data 

- Skimr
- Naniar
- DataMaid

## Data Wrangling and Analysis
    
### General tips

- Restart session often    
- Create as few objects as possible   
- Load all data at top


# Reporting Results

## RMarkdown

Explain how I didn't use RMarkdown for a long time and really missed out

### General practices

#### I typically don't name code chunks

#### Use TOC

#### YAML

- https://github.com/r-lib/ymlthis

#### Parameterized reports

#### Misc

- https://github.com/ThinkR-open/remedy

### What format to knit to when


#### Word

Using Word reference documents for style

#### PDF

I basically don't because I'm scared off by LaTeX

#### HTML

##### Distill

##### Bookdown

https://alison.rbind.io/talk/2019-rsc-bookdown/

##### Pagedown

#### Dashboards

##### Flexdashboard

##### crosstalk

##### Shiny


## Data Visualization

### Themes I Like

### Fonts

extrafont package

### ggplot extensions

### Formatting numbers etc

- Twitter tip to not use scientific notation: https://twitter.com/ecologyofgavin/status/1188865515059585025
- scales package

### Mapping

#### General packages
- tmap
- leaflet
- ggplot 
- mapview

#### Geocoding

- ggmap
- https://rdrr.io/cran/tmaptools/man/geocode_OSM.html
- opencage


### Tables

See blog post


# What I Do When Things Go Wrong (and They Always Do)

## Guides to getting help in R

- https://socviz.co/appendix.html#a-little-more-about-r
- https://sctyner.github.io/rhelp.html

# Other Resources

- https://whattheyforgot.org/


